// This is Random Number Guessing Game
// Guessing the number in lowest attempts will be the winner

// with Guide..

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    // In This variable we are going to store the random number.
    int number, guess, nguesses = 1;

    // we will generate the random number using << srand() >>
    // we can give a value to the srand() suppose time(0) it will generate the number according to this number.
    srand(time(0));

    // here we are storing the random number to the << number >> named variable
    // number = rand();

    // Now the problem is that it is generating the random number till infinity
    number = rand() % 100 + 1; // now this is set to generate the  random no from 1 to 100

    // here we are printing the random number which is generated by the compiler
    // printf("\n > %d <\n", number);

    do
    {
        // Taking input from the user and match with the system generated Random number either it is equal or not.
        printf("Guess the number between 1 to 100. : ");
        scanf("%d", &guess);

        // Just Uncomment below code to make this process automatic because it will automatically guess the number and match this number with the previous generated number and show that how much attempts it takes to guess the number right.
        // srand(time(0));
        // guess = rand() % 100 + 2;

        printf("The system Generated random number for matching is :> %d\n", guess);

        if (guess > number)
        {
            printf("Lower number please....!\n");
        }
        else if (guess < number)
        {
            printf("Higher number please....!\n");
        }

        // this statement checks in how much attempts you Guess the right number which was generated
        else
        {
            printf("You guessed it in %d attempts.\n", nguesses);
        }

        // here the the number of attempts will be incremented after each iteration
        nguesses++;

        // here is the condition of the loop to execute the loop again and again..
    } while (guess != number);

    return 0;
}

// below is the Demo i guessed it in 3 Attempts

/*
Guess the number between 1 to 100. : 10
Higher number please....!
Guess the number between 1 to 100. : 20
Lower number please....!
Guess the number between 1 to 100. : 19
You guessed it in 3 attempts.
*/